version: '3.2'

services:
  redis:
    image: bitnami/redis:latest
    command: /opt/bitnami/scripts/redis/run.sh --appendonly no
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:
  mysql-data: